INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
('WEAPON_PISTOL', 'Pistol', 20, 0, 1),
('WEAPON_ASSAULTRIFLE', 'Assualt Riffle', 2, 0, 1),
('WEAPON_PUMPSHOTGUN', 'Pump Shotgun', 2, 0, 1),
('WEAPON_SMOKEGRENADE', 'Smoke grenade', 25, 0, 1),
('WEAPON_MICROSMG', 'Micro SMG', 5, 0, 1),
('WEAPON_FLASHLIGHT', 'Flashlight', 20, 0, 1),
('WEAPON_PETROLCAN', 'Jerry Can', 2, 0, 1),
('WEAPON_SMG', 'SMG', 2, 0, 1),
('WEAPON_CARBINERIFLE', 'Carbine Rifle', 2, 0, 1),
('WEAPON_MARKSMANRIFLE', 'Marksman Rifle', 2, 0, 1),
('WEAPON_NIGHTSTICK', 'Nightstick', 10, 0, 1),
('WEAPON_COMBATPISTOL', 'Combat Pistol', 10, 0, 1),
('WEAPON_STUNGUN', 'Stungun', 10, 0, 1),
('WEAPON_BZGAS', 'BZGAS', 25, 0, 1),
('WEAPON_APPISTOL', 'AP Pistol', 10, 0, 1),
('WEAPON_PISTOL50', 'Pistol Cal 50', 5, 0, 1),
('WEAPON_ASSAULTSMG', 'Assualt SMG', 2, 0, 1),
('WEAPON_VINTAGEPISTOL', 'Vintage Pistol', 15, 0, 1),
('WEAPON_MUSKET', 'Musket', 2, 0, 1),
('WEAPON_SPECIALCARBINE', 'Special Carbine', 2, 0, 1),
('WEAPON_SWITCHBLADE', 'Switch Blade', 20, 0, 1),
('WEAPON_KNUCKLE', 'Knuckle Duster', 20, 0, 1),
('WEAPON_SNSPISTOL', 'SNS Pistol', 15, 0, 1),
('mWEAPON_PISTOL', 'Pistol Ammo', 1000, 0, 1),
('mWEAPON_ASSAULTRIFLE', 'Assualt Riffle Ammo', 1000, 0, 1),
('mWEAPON_PUMPSHOTGUN', 'Pump Shotgun Ammo', 1000, 0, 1),
('mWEAPON_MICROSMG', 'Micro SMG Ammo', 1000, 0, 1),
('mWEAPON_SMG', 'SMG Ammo', 1000, 0, 1),
('mWEAPON_CARBINERIFLE', 'Carbine Riffle Ammo', 1000, 0, 1),
('mWEAPON_MARKSMANRIFLE', 'Markman Riffle Ammo', 1000, 0, 1),
('mWEAPON_COMBATPISTOL', 'Compat Pistol Ammo', 1000, 0, 1),
('mWEAPON_APPISTOL', 'AP Pistol Ammo', 1000, 0, 1),
('mWEAPON_PISTOL50', 'Pistol Cal 50 Ammo', 1000, 0, 1),
('mWEAPON_ASSAULTSMG', 'Assualt SMG Ammo', 1000, 0, 1),
('mWEAPON_VINTAGEPISTOL', 'Vintage Pistol Ammo', 1000, 0, 1),
('mWEAPON_MUSKET', 'Musket Ammo', 1000, 0, 1),
('mWEAPON_SPECIALCARBINE', 'Special Carbine Ammo', 1000, 0, 1),
('mWEAPON_SNSPISTOL', 'SNS Pistol Ammo', 1000, 0, 1);



